### ISSUE TITLE
Canada, Prince Edward Island

### ISSUE THREAD

**Issue by fisharebest** [webtrees/geodata#1]

**Comment by fisharebest** [comment]
[Kings.txt](https://github.com/fisharebest/webtrees-geodata/files/640704/Kings.txt)
[Prince.txt](https://github.com/fisharebest/webtrees-geodata/files/640705/Prince.txt)
[Queens.txt](https://github.com/fisharebest/webtrees-geodata/files/640706/Queens.txt)

**Comment by ghost** [comment]
Here is the Prince Edward Island data.geojson file.
[data.geojson.txt](https://github.com/fisharebest/webtrees-geodata/files/642608/data.geojson.txt)

**Comment by fisharebest** [comment]
I have added all the places.

I have merged the coordinates from the webtrees GM module.

There are still some places without coordinates.

I'll add some code to identify these.
