### ISSUE TITLE
PEI - Queens county - CSV file

### ISSUE THREAD

**Issue by ghost** [webtrees/geodata#10]
[Canada-Prince_Edward_Island-Queens-places.zip](https://github.com/fisharebest/webtrees-geodata/files/644563/Canada-Prince_Edward_Island-Queens-places.zip)

**Comment by fisharebest** [comment]
This file has two places called "Bayview" with different coordinates.

If these are two different places, they need something (a nearby town?) to identify them.
e.q. "Bayview (Bigtown)" and "Bayview (Riverville)".

**Comment by ghost** [comment]
My mistake, sorry. There is only one Bayview. Coordinates: W63.43604, N46.47468
Would you please correct the file?

**Comment by fisharebest** [comment]
Done!
