### ISSUE TITLE
Nova Scotia Counties - csv file

### ISSUE THREAD

**Issue by ghost** [webtrees/geodata#11]
[Canada-Nova_Scotia-places.zip](https://github.com/fisharebest/webtrees-geodata/files/644636/Canada-Nova_Scotia-places.zip)

**Comment by fisharebest** [comment]
https://en.wikipedia.org/wiki/Nova_Scotia lists two other counties - Victoria and Guysborough

Should I add these two?

**Comment by fisharebest** [comment]
I added them.

**Comment by ghost** [comment]
I forgot them. :-( 
Thanks.
