### ISSUE TITLE
Canada, Quebec

### ISSUE THREAD

**Issue by fisharebest** [webtrees/geodata#2]
[cities.txt](https://github.com/fisharebest/webtrees-geodata/files/640716/cities.txt)
[villages_and_municipalities.txt](https://github.com/fisharebest/webtrees-geodata/files/640717/villages_and_municipalities.txt)

**Comment by ghost** [comment]
Got it! Next time, I'll use the issue tracker. :-)

**Comment by fisharebest** [comment]
I've added these, and merged in the coordinates from the webtrees/googlemap files.
