### ISSUE TITLE
Canada - wip

### ISSUE THREAD

**Issue by ghost** [webtrees/geodata#6]
Why do I see the word "wip" besides Canada?
All the others have the word "webtrees-geodata"

**Comment by ghost** [comment]
Found my answer! Please ignore.

**Comment by fisharebest** [comment]
Just the commit comments.

wip = work in progress.

In the future, I'll create version numbers, etc.
Until version 1.0.0 is ready, I'll "merge" all the commits into a single file.  This will minimise the size of the repository that people need to download.
