### ISSUE TITLE
Yukon Territory - data.geojson file

### ISSUE THREAD

**Issue by ghost** [webtrees/geodata#7]
Coding errors in that file? Impossible to display the map

**Comment by fisharebest** [comment]
To find these errors, you can click the "raw" button to see the JSON data.
You can then copy/paste it into http://jsonlint.com

This says there are no errors in the syntax JSON.
So it must be an issue with the data.  Missing/invalid coords, etc.
I'll check later

**Comment by fisharebest** [comment]
Even better: http://geojsonlint.com tells us the exact error.

**Comment by ghost** [comment]
Please ignore. That was coded "wip" when I tried to display the map. Thanks.
